services:
  - type: web
    name: emisoras-backend
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn emisoras_backend.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false
