# Generated by Django 5.2.14 on 2026-05-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emisora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cadena', models.CharField(db_index=True, max_length=100)),
                ('ciudad', models.CharField(db_index=True, max_length=100)),
                ('url', models.URLField()),
                ('via', models.CharField(default='streamtheworld', max_length=50)),
                ('codename', models.CharField(blank=True, default='', max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Emisora',
                'verbose_name_plural': 'Emisoras',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
